name: 'Jira Api Functions'
description: 'Jira Api Functions'
inputs:
  username:  # id of input
    description: 'Atlassian Jira AUTH Username'
    required: true
    default: ''
  token:  # id of input
    description: 'Atlassian Jira AUTH Token'
    required: true
    default: ''
  project-key:  # id of input
    description: 'Jira Project Key'
    required: true
    default: ''
  issue-type:  # id of input
    description: 'Jira Issue Type (Ex: Bug)'
    required: true
    default: ''
  content:  # id of input
    description: 'Content of the issue'


outputs:
  created-issue-id: # id of output
    description: 'The ID of the issue that was just created'
runs:
  using: 'node16'
  main: 'index.js'